version: "3.2"
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ..:/var/www/html/
      - ./logs/mysql/:/var/log/mysql/
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html/
      - ./logs/apache/:/var/log/apache2/
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
networks:
  frontend:
  backend: